name: Deploy to Amazon Linux

on:
  push:
    branches: [ main ]  # ou 'master' selon votre branche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}      # L'IP de votre serveur
        username: ${{ secrets.USERNAME }} # Souvent 'ec2-user' ou 'ubuntu'
        key: ${{ secrets.SSH_KEY }}    # Votre clé privée (.pem)
        script: |
          cd /chemin/vers/votre/dossier
          git pull origin main
          npm install                # Si vous avez ajouté des dépendances
          pm2 restart all            # Redémarre l'app Node.js
